name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
  
  code-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      env: 
        COVERAGE_THRESHOLD: 80
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Code coverage
      run: |
        go test -race -coverprofile=coverage.out -covermode=atomic ./...
        coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
        if [ 1 -eq "$(echo "${coverage} < ${CODE_COVERAGE}" | bc)" ]
        then
          echo "Insufficient test coverage, threshold=$COVERAGE_THRESHOLD, coverage= $coverage"
          exit 1
        fi
